### ISSUE TITLE
Explanation on KeyPom Arguments

### ISSUE THREAD

**Issue by jaswinder6991** [keypom/keypom#82]
I am not really sure how KeyPom Arguments are different that what was already there.
From the FC tests, I took below lines of code.
https://github.com/keypom/keypom/blob/main/deploy/function-call/fc-create.js

`let fc_data = {
	methods: [
		[{
			receiver_id: "dev-1664052531433-97566156431683",
			method_name: "nft_mint",
			args: JSON.stringify({
				"foo": "bar",
				"keypom_args": {
					"account_id_field": "receiver_id",
					"drop_id_field" : "mint_id"
				}
			}),
			attached_deposit: parseNearAmount("1"),
			account_id_field: "receiver_id",
			drop_id_field: "mint_id"
		}]
	]
}`

Here why is keypom_args added to the function args? As in nft_mint does not excepts such an argument? In the earlier version, you would only pass arguments that the custom function needed. Also, in the outside there is already account_id_field and drop_id_field. I read the description and it was not clear to me.

**Comment by BenKurrek** [comment]
Keypom Arguments is a struct that is automatically injected into the arguments that get fired off to the cross contract call. The receiver contract can choose to either use this struct or not. The Keypom Args will ALWAYS be attached and it is up to the receiver as to what they want to do with that information.

The args essentially tell the receiver contract what information is automatically populated by keypom (drop ID, claimed account Id, key ID etc..) and what information was MANUALLY entered by the funder when the drop was created. This is very important since there are serious security implications if the keypom args are NOT sent to the receiver contract.

Please see [this](https://keypom.github.io/keypom/keypom/#motivation) section in our docs as to the motivation and an in-depth example. Let me know if this makes - happy to expand on it if it isn't clear.
